const RABBITMQ_AMQP_URI = process.env.RABBITMQ_AMQP_URI
const RABBITMQ_EXCHANGE = process.env.RABBITMQ_EXCHANGE
const RABBITMQ_LOGGER_QUEUE = process.env.RABBITMQ_LOGGER_QUEUE
const RABBITMQ_CONSUMER_QUEUE = process.env.RABBITMQ_CONSUMER_QUEUE

module.exports = {
  RABBITMQ_AMQP_URI,
  RABBITMQ_EXCHANGE,
  RABBITMQ_LOGGER_QUEUE,
  RABBITMQ_CONSUMER_QUEUE
}
