version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=kajame
      - RABBITMQ_DEFAULT_PASS=111111
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq

  publisher:
    container_name: publisher
    ports:
      - 2000:2000
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    environment: 
      - SERVICE_NAME=publisher
    volumes:
      - ./backend:/app
      - /app/node_modules

  logger:
    container_name: logger
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    environment: 
      - SERVICE_NAME=logger
    volumes:
      - ./backend:/app
      - /app/node_modules

  consumer1:
    container_name: consumer-1
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    environment: 
      - SERVICE_NAME=consumer
    volumes:
      - ./backend:/app
      - /app/node_modules

  consumer2:
    container_name: consumer-2
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    environment: 
      - SERVICE_NAME=consumer
    volumes:
      - ./backend:/app
      - /app/node_modules